// BIOMD0000000007

diagram = [
{ data: { id: 'Wee1',label: 'Wee1'}},
{ data: { id: 'Cig2_Cdc2',label: 'Cig2_Cdc2'}},
{ data: { id: 'Cdc25 production & degradation_mod',},classes: 'mid'},
{ data: { id: 'M-phasePromotingFactor',label: 'M-phasePromotingFactor'}},
{ data: { id: 'Wee1 production & degradation_mod',},classes: 'mid'},
{ data: { id: 'BoundUbiquitinProtease1',label: 'BoundUbiquitinProtease1'}},
{ data: { id: 'ubiquitinProtease2',label: 'ubiquitinProtease2'}},
{ data: { id: 'Cig2_Cdc2_Rum1',label: 'Cig2_Cdc2_Rum1'}},
{ data: { id: 'Cdc13_P-Cdc2_deg',label: 'Cdc13_P-Cdc2_deg'}, classes: 'deg'},
{ data: { id: 'BoundCdc25',label: 'BoundCdc25'}},
{ data: { id: 'Cdc13_P-Cdc2_Rum1',label: 'Cdc13_P-Cdc2_Rum1'}},
{ data: { id: 'Cdc13 degradation in Cdc13_P-Cdc2_mod',},classes: 'mid'},
{ data: { id: 'FreeRum1_src',label: 'FreeRum1_src'}, classes: 'src'},
{ data: { id: 'IE production & degradation_mod',},classes: 'mid'},
{ data: { id: 'Cdc2 phosphorylation_mod',},classes: 'mid'},
{ data: { id: 'binding of Rum1 with Cdc13_Cdc2_mod',},classes: 'mid'},
{ data: { id: 'Cig2 degradation in Cig2_Cdc2_mod',},classes: 'mid'},
{ data: { id: 'Cig2_Cdc2_src',label: 'Cig2_Cdc2_src'}, classes: 'src'},
{ data: { id: 'Cdc25',label: 'Cdc25'}},
{ data: { id: 'BoundIntermediaryEnzyme',label: 'BoundIntermediaryEnzyme'}},
{ data: { id: 'Rum1 degradation by SPF_mod',},classes: 'mid'},
{ data: { id: 'FreeRum1',label: 'FreeRum1'}},
{ data: { id: 'UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_P-Cdc2_mod',},classes: 'mid'},
{ data: { id: 'UbE production & degradation_mod',},classes: 'mid'},
{ data: { id: 'UbE2 production & degradation_mod',},classes: 'mid'},
{ data: { id: 'S-phasePromotingFactor',label: 'S-phasePromotingFactor'}},
{ data: { id: 'Cdc13_Cdc2',label: 'Cdc13_Cdc2'}},
{ data: { id: 'binding of Rum1 with Cdc13_P-Cdc2_mod',},classes: 'mid'},
{ data: { id: 'BoundWee1',label: 'BoundWee1'}},
{ data: { id: 'ubiquitinProtease1',label: 'ubiquitinProtease1'}},
{ data: { id: 'Cdc13_P-Cdc2',label: 'Cdc13_P-Cdc2'}},
{ data: { id: 'IntermediaryEnzyme',label: 'IntermediaryEnzyme'}},
{ data: { id: 'BoundUbiquitinProtease2',label: 'BoundUbiquitinProtease2'}},
{ data: { id: 'Cdc13_Cdc2_Rum1',label: 'Cdc13_Cdc2_Rum1'}},
{ data: { id: 'Cig2_Cdc2_deg',label: 'Cig2_Cdc2_deg'}, classes: 'deg'},
{ data: { id: 'UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_Cdc2_mod',},classes: 'mid'},
{ data: { id: 'Binding of Rum1 to Cig2_Cdc2_mod',},classes: 'mid'},
{ data: { id: 'Cdc13_Cdc2_src',label: 'Cdc13_Cdc2_src'}, classes: 'src'},
{ data: { id: 'Cdc13_Cdc2_deg',label: 'Cdc13_Cdc2_deg'}, classes: 'deg'},
{ data: { id: 'Cdc13 degradation in Cdc13_Cdc2_mod',},classes: 'mid'},
{ data: { id: 'FreeRum1_deg',label: 'FreeRum1_deg'}, classes: 'deg'},
{ data: { id: 'r0',source: 'Cdc13_Cdc2_src',target: 'Cdc13_Cdc2',tcID: '(Cdc13_Cdc2 creation).Flux',label: 'k1/Cell'}, classes: 'reaction'},
{ data: { id: 'r1',source: 'Cig2_Cdc2_src',target: 'Cig2_Cdc2',tcID: '(Cig2_Cdc2 creation).Flux',label: 'k5/Cell'}, classes: 'reaction'},
{ data: { id: 'r2',source: 'Cdc13_Cdc2',target: 'Cdc2 phosphorylation_mod',tcID: '(Cdc2 phosphorylation).Flux',label: '(G2K*Cell*kwee-k25*(PG2*Cell))/Cell'}, classes: 'reaction'},
{ data: { id: 'r3',source: 'Cdc2 phosphorylation_mod',target: 'Cdc13_P-Cdc2',tcID: '(Cdc2 phosphorylation).Flux',label: '(G2K*Cell*kwee-k25*(PG2*Cell))/Cell'}, classes: 'reaction'},
{ data: { id: 'r4',source: 'Wee1',target: 'Cdc2 phosphorylation_mod',tcID: 'Wee1',label: '(G2K*Cell*kwee-k25*(PG2*Cell))/Cell'}, classes: 'mod'},
{ data: { id: 'r5',source: 'Cdc25',target: 'Cdc2 phosphorylation_mod',tcID: 'Cdc25',label: '(G2K*Cell*kwee-k25*(PG2*Cell))/Cell'}, classes: 'mod'},
{ data: { id: 'r6',source: 'Cdc13_Cdc2',target: 'binding of Rum1 with Cdc13_Cdc2_mod',tcID: '(binding of Rum1 with Cdc13_Cdc2).Flux',label: '(G2K*Cell*k7*(R*Cell)-G2R*Cell*k7r)/Cell'}, classes: 'reaction'},
{ data: { id: 'r7',source: 'FreeRum1',target: 'binding of Rum1 with Cdc13_Cdc2_mod',tcID: '(binding of Rum1 with Cdc13_Cdc2).Flux',label: '(G2K*Cell*k7*(R*Cell)-G2R*Cell*k7r)/Cell'}, classes: 'reaction'},
{ data: { id: 'r8',source: 'binding of Rum1 with Cdc13_Cdc2_mod',target: 'Cdc13_Cdc2_Rum1',tcID: '(binding of Rum1 with Cdc13_Cdc2).Flux',label: '(G2K*Cell*k7*(R*Cell)-G2R*Cell*k7r)/Cell'}, classes: 'reaction'},
{ data: { id: 'r9',source: 'Cdc13_P-Cdc2',target: 'binding of Rum1 with Cdc13_P-Cdc2_mod',tcID: '(binding of Rum1 with Cdc13_P-Cdc2).Flux',label: '(k7*(PG2*Cell)*(R*Cell)-k7r*(PG2R*Cell))/Cell'}, classes: 'reaction'},
{ data: { id: 'r10',source: 'FreeRum1',target: 'binding of Rum1 with Cdc13_P-Cdc2_mod',tcID: '(binding of Rum1 with Cdc13_P-Cdc2).Flux',label: '(k7*(PG2*Cell)*(R*Cell)-k7r*(PG2R*Cell))/Cell'}, classes: 'reaction'},
{ data: { id: 'r11',source: 'binding of Rum1 with Cdc13_P-Cdc2_mod',target: 'Cdc13_P-Cdc2_Rum1',tcID: '(binding of Rum1 with Cdc13_P-Cdc2).Flux',label: '(k7*(PG2*Cell)*(R*Cell)-k7r*(PG2R*Cell))/Cell'}, classes: 'reaction'},
{ data: { id: 'r12',source: 'Cdc13_Cdc2_Rum1',target: 'Cdc13_Cdc2',tcID: '(Rum1 degradation in Rum1_Cdc13_Cdc2).Flux',label: 'k4*Cdc13_Cdc2_Rum1'}, classes: 'reaction'},
{ data: { id: 'r13',source: 'FreeRum1',target: 'FreeRum1_deg',tcID: '(Rum1 degradation in solution).Flux',label: 'k4*FreeRum1'}, classes: 'reaction'},
{ data: { id: 'r14',source: 'Cdc13_P-Cdc2_Rum1',target: 'Cdc13_P-Cdc2',tcID: '(Rum1 degradation in Rum1_Cdc13_P-Cdc2).Flux',label: 'k4*Cdc13_P-Cdc2_Rum1'}, classes: 'reaction'},
{ data: { id: 'r15',source: 'Cig2_Cdc2_Rum1',target: 'Cig2_Cdc2',tcID: '(Rum1 degradation in Rum1_Cig2_Cdc2).Flux',label: 'k4*Cig2_Cdc2_Rum1'}, classes: 'reaction'},
{ data: { id: 'r16',source: 'Cdc13_Cdc2',target: 'Cdc13 degradation in Cdc13_Cdc2_mod',tcID: '(Cdc13 degradation in Cdc13_Cdc2).Flux',label: 'k2*Cdc13_Cdc2'}, classes: 'reaction'},
{ data: { id: 'r17',source: 'Cdc13 degradation in Cdc13_Cdc2_mod',target: 'Cdc13_Cdc2_deg',tcID: '(Cdc13 degradation in Cdc13_Cdc2).Flux',label: 'k2*Cdc13_Cdc2'}, classes: 'reaction'},
{ data: { id: 'r18',source: 'ubiquitinProtease1',target: 'Cdc13 degradation in Cdc13_Cdc2_mod',tcID: 'ubiquitinProtease1',label: 'k2*Cdc13_Cdc2'}, classes: 'mod'},
{ data: { id: 'r19',source: 'Cdc13_P-Cdc2',target: 'Cdc13 degradation in Cdc13_P-Cdc2_mod',tcID: '(Cdc13 degradation in Cdc13_P-Cdc2).Flux',label: 'k2*Cdc13_P-Cdc2'}, classes: 'reaction'},
{ data: { id: 'r20',source: 'Cdc13 degradation in Cdc13_P-Cdc2_mod',target: 'Cdc13_P-Cdc2_deg',tcID: '(Cdc13 degradation in Cdc13_P-Cdc2).Flux',label: 'k2*Cdc13_P-Cdc2'}, classes: 'reaction'},
{ data: { id: 'r21',source: 'ubiquitinProtease1',target: 'Cdc13 degradation in Cdc13_P-Cdc2_mod',tcID: 'ubiquitinProtease1',label: 'k2*Cdc13_P-Cdc2'}, classes: 'mod'},
{ data: { id: 'r22',source: 'Cig2_Cdc2',target: 'Cig2 degradation in Cig2_Cdc2_mod',tcID: '(Cig2 degradation in Cig2_Cdc2).Flux',label: 'k6*Cig2_Cdc2'}, classes: 'reaction'},
{ data: { id: 'r23',source: 'Cig2 degradation in Cig2_Cdc2_mod',target: 'Cig2_Cdc2_deg',tcID: '(Cig2 degradation in Cig2_Cdc2).Flux',label: 'k6*Cig2_Cdc2'}, classes: 'reaction'},
{ data: { id: 'r24',source: 'ubiquitinProtease2',target: 'Cig2 degradation in Cig2_Cdc2_mod',tcID: 'ubiquitinProtease2',label: 'k6*Cig2_Cdc2'}, classes: 'mod'},
{ data: { id: 'r25',source: 'Cdc13_P-Cdc2_Rum1',target: 'FreeRum1',tcID: '(Cdc13 degradation in Rum1_Cdc13_P-Cdc2).Flux',label: 'k2prime*Cdc13_P-Cdc2_Rum1'}, classes: 'reaction'},
{ data: { id: 'r26',source: 'Cdc13_Cdc2_Rum1',target: 'FreeRum1',tcID: '(Cdc13 degradation in Rum1_Cdc13_Cdc2).Flux',label: 'k2prime*Cdc13_Cdc2_Rum1'}, classes: 'reaction'},
{ data: { id: 'r27',source: 'Cig2_Cdc2_Rum1',target: 'FreeRum1',tcID: '(Cig2 degradation in Rum1_Cig2_Cdc2).Flux',label: 'k6prime*Cig2_Cdc2_Rum1'}, classes: 'reaction'},
{ data: { id: 'r28',source: 'Cig2_Cdc2',target: 'Binding of Rum1 to Cig2_Cdc2_mod',tcID: '(Binding of Rum1 to Cig2_Cdc2).Flux',label: '(G1K*Cell*k8*(R*Cell)-G1R*Cell*k8r)/Cell'}, classes: 'reaction'},
{ data: { id: 'r29',source: 'FreeRum1',target: 'Binding of Rum1 to Cig2_Cdc2_mod',tcID: '(Binding of Rum1 to Cig2_Cdc2).Flux',label: '(G1K*Cell*k8*(R*Cell)-G1R*Cell*k8r)/Cell'}, classes: 'reaction'},
{ data: { id: 'r30',source: 'Binding of Rum1 to Cig2_Cdc2_mod',target: 'Cig2_Cdc2_Rum1',tcID: '(Binding of Rum1 to Cig2_Cdc2).Flux',label: '(G1K*Cell*k8*(R*Cell)-G1R*Cell*k8r)/Cell'}, classes: 'reaction'},
{ data: { id: 'r31',source: 'Cdc13_Cdc2_Rum1',target: 'UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_Cdc2_mod',tcID: '(UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_Cdc2).Flux',label: 'k2*Cdc13_Cdc2_Rum1'}, classes: 'reaction'},
{ data: { id: 'r32',source: 'UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_Cdc2_mod',target: 'FreeRum1',tcID: '(UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_Cdc2).Flux',label: 'k2*Cdc13_Cdc2_Rum1'}, classes: 'reaction'},
{ data: { id: 'r33',source: 'ubiquitinProtease1',target: 'UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_Cdc2_mod',tcID: 'ubiquitinProtease1',label: 'k2*Cdc13_Cdc2_Rum1'}, classes: 'mod'},
{ data: { id: 'r34',source: 'Cdc13_P-Cdc2_Rum1',target: 'UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_P-Cdc2_mod',tcID: '(UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_P-Cdc2).Flux',label: 'k2*Cdc13_P-Cdc2_Rum1'}, classes: 'reaction'},
{ data: { id: 'r35',source: 'UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_P-Cdc2_mod',target: 'FreeRum1',tcID: '(UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_P-Cdc2).Flux',label: 'k2*Cdc13_P-Cdc2_Rum1'}, classes: 'reaction'},
{ data: { id: 'r36',source: 'ubiquitinProtease1',target: 'UbE mediated degradation of Cdc13_Cdc2 in Rum1_Cdc13_P-Cdc2_mod',tcID: 'ubiquitinProtease1',label: 'k2*Cdc13_P-Cdc2_Rum1'}, classes: 'mod'},
{ data: { id: 'r37',source: 'FreeRum1_src',target: 'FreeRum1',tcID: '(Rum1 creation).Flux',label: 'k3/Cell'}, classes: 'reaction'},
{ data: { id: 'r38',source: 'FreeRum1',target: 'Rum1 degradation by SPF_mod',tcID: '(Rum1 degradation by SPF).Flux',label: 'kp*Mass*R*(SPF*Cell)/(Kmp+R*Cell)'}, classes: 'reaction'},
{ data: { id: 'r39',source: 'Rum1 degradation by SPF_mod',target: 'FreeRum1_deg',tcID: '(Rum1 degradation by SPF).Flux',label: 'kp*Mass*R*(SPF*Cell)/(Kmp+R*Cell)'}, classes: 'reaction'},
{ data: { id: 'r40',source: 'S-phasePromotingFactor',target: 'Rum1 degradation by SPF_mod',tcID: 'S-phasePromotingFactor',label: 'kp*Mass*R*(SPF*Cell)/(Kmp+R*Cell)'}, classes: 'mod'},
{ data: { id: 'r41',source: 'BoundIntermediaryEnzyme',target: 'IE production & degradation_mod',tcID: '(IE production & degradation).Flux',label: '(IEB*Cell*ki*(MPF*Cell)/(IEB*Cell+Kmi)-IE*Cell*kir/(IE*Cell+Kmir))/Cell'}, classes: 'reaction'},
{ data: { id: 'r42',source: 'IE production & degradation_mod',target: 'IntermediaryEnzyme',tcID: '(IE production & degradation).Flux',label: '(IEB*Cell*ki*(MPF*Cell)/(IEB*Cell+Kmi)-IE*Cell*kir/(IE*Cell+Kmir))/Cell'}, classes: 'reaction'},
{ data: { id: 'r43',source: 'M-phasePromotingFactor',target: 'IE production & degradation_mod',tcID: 'M-phasePromotingFactor',label: '(IEB*Cell*ki*(MPF*Cell)/(IEB*Cell+Kmi)-IE*Cell*kir/(IE*Cell+Kmir))/Cell'}, classes: 'mod'},
{ data: { id: 'r44',source: 'BoundUbiquitinProtease1',target: 'UbE production & degradation_mod',tcID: '(UbE production & degradation).Flux',label: '(IE*Cell*ku*(UbEB*Cell)/(Kmu+UbEB*Cell)-kur*(UbE*Cell)/(Kmur+UbE*Cell))/Cell'}, classes: 'reaction'},
{ data: { id: 'r45',source: 'UbE production & degradation_mod',target: 'ubiquitinProtease1',tcID: '(UbE production & degradation).Flux',label: '(IE*Cell*ku*(UbEB*Cell)/(Kmu+UbEB*Cell)-kur*(UbE*Cell)/(Kmur+UbE*Cell))/Cell'}, classes: 'reaction'},
{ data: { id: 'r46',source: 'IntermediaryEnzyme',target: 'UbE production & degradation_mod',tcID: 'IntermediaryEnzyme',label: '(IE*Cell*ku*(UbEB*Cell)/(Kmu+UbEB*Cell)-kur*(UbE*Cell)/(Kmur+UbE*Cell))/Cell'}, classes: 'mod'},
{ data: { id: 'r47',source: 'BoundUbiquitinProtease2',target: 'UbE2 production & degradation_mod',tcID: '(UbE2 production & degradation).Flux',label: '(ku2*(MPF*Cell)*(UbE2B*Cell)/(Kmu2+UbE2B*Cell)-kur2*(UbE2*Cell)/(Kmur2+UbE2*Cell))/Cell'}, classes: 'reaction'},
{ data: { id: 'r48',source: 'UbE2 production & degradation_mod',target: 'ubiquitinProtease2',tcID: '(UbE2 production & degradation).Flux',label: '(ku2*(MPF*Cell)*(UbE2B*Cell)/(Kmu2+UbE2B*Cell)-kur2*(UbE2*Cell)/(Kmur2+UbE2*Cell))/Cell'}, classes: 'reaction'},
{ data: { id: 'r49',source: 'M-phasePromotingFactor',target: 'UbE2 production & degradation_mod',tcID: 'M-phasePromotingFactor',label: '(ku2*(MPF*Cell)*(UbE2B*Cell)/(Kmu2+UbE2B*Cell)-kur2*(UbE2*Cell)/(Kmur2+UbE2*Cell))/Cell'}, classes: 'mod'},
{ data: { id: 'r50',source: 'BoundWee1',target: 'Wee1 production & degradation_mod',tcID: '(Wee1 production & degradation).Flux',label: '(kwr*(Wee1B*Cell)/(Kmwr+Wee1B*Cell)-kw*(MPF*Cell)*(Wee1*Cell)/(Kmw+Wee1*Cell))/Cell'}, classes: 'reaction'},
{ data: { id: 'r51',source: 'Wee1 production & degradation_mod',target: 'Wee1',tcID: '(Wee1 production & degradation).Flux',label: '(kwr*(Wee1B*Cell)/(Kmwr+Wee1B*Cell)-kw*(MPF*Cell)*(Wee1*Cell)/(Kmw+Wee1*Cell))/Cell'}, classes: 'reaction'},
{ data: { id: 'r52',source: 'M-phasePromotingFactor',target: 'Wee1 production & degradation_mod',tcID: 'M-phasePromotingFactor',label: '(kwr*(Wee1B*Cell)/(Kmwr+Wee1B*Cell)-kw*(MPF*Cell)*(Wee1*Cell)/(Kmw+Wee1*Cell))/Cell'}, classes: 'mod'},
{ data: { id: 'r53',source: 'BoundCdc25',target: 'Cdc25 production & degradation_mod',tcID: '(Cdc25 production & degradation).Flux',label: '(Cdc25B*Cell*kc*(MPF*Cell)/(Cdc25B*Cell+Kmc)-Cdc25*Cell*kcr/(Cdc25*Cell+Kmcr))/Cell'}, classes: 'reaction'},
{ data: { id: 'r54',source: 'Cdc25 production & degradation_mod',target: 'Cdc25',tcID: '(Cdc25 production & degradation).Flux',label: '(Cdc25B*Cell*kc*(MPF*Cell)/(Cdc25B*Cell+Kmc)-Cdc25*Cell*kcr/(Cdc25*Cell+Kmcr))/Cell'}, classes: 'reaction'},
{ data: { id: 'r55',source: 'M-phasePromotingFactor',target: 'Cdc25 production & degradation_mod',tcID: 'M-phasePromotingFactor',label: '(Cdc25B*Cell*kc*(MPF*Cell)/(Cdc25B*Cell+Kmc)-Cdc25*Cell*kcr/(Cdc25*Cell+Kmcr))/Cell'}, classes: 'mod'}
];
